on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  bump:
    name: Bump version in setup.py
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.version }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        sed -i "/VERSION =/c\VERSION = '${{ github.event.inputs.version }}'" setup.py
        git diff
    - uses: EndBug/add-and-commit@v9
      with:
        add: setup.py
        tag: -a "${{ github.event.inputs.version }}" -m "Version ${{ github.event.inputs.version }}"
    - uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
